version: '3'

services:

  postgres_db:
    restart: always
    image: postgres
    container_name: app_store_pg_db
    volumes:
      - app_store_pg_db:/var/lib/postgresql/data
    env_file: .env
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER_NAME}
      - POSTGRES_PASSWORD=${DATABASE_USER_PASSWORD}
      - TZ=UTC

  web:
    restart: always
    build: ./app
    image: app_store
    container_name: app_store_web
    volumes:
      - ./app:/app
    ports:
      - "${WEB_ADDR}:8000"
    env_file: .env
    command: gunicorn --bind 0.0.0.0:8000 appstore.wsgi 
    entrypoint: /app/entrypoint.sh
    depends_on:
      - postgres_db

volumes:
  app_store_pg_db:
